window.KANDONG_CONFIG = {
  SUPABASE_URL: 'https://gsgzrbohigoiuiqfbzzr.supabase.co',
  SUPABASE_ANON_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdzZ3pyYm9oaWdvaXVpcWZienpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTExODYwNjcsImV4cCI6MjEwNjc',
  APP_NAME: 'Kandong',
  VERSION: '1.2.1',
  CACHE_NAME: 'kandong-v1.2.1',
  FARE_BASE: 60,
  FARE_MAX: 150,
  POLL_INTERVAL_MS: 4000,
  // name + area for distinct suggestions
  PLACES: [
    { name: 'SM City', area: 'Downtown' },
    { name: 'SM Annex', area: 'Downtown' },
    { name: 'Town Center', area: 'Central' },
    { name: 'City Hall', area: 'Government District' },
    { name: 'Main Terminal', area: 'Transport Hub' },
    { name: 'Central Market', area: 'Market Area' },
    { name: 'Public Plaza', area: 'Central' },
    { name: 'Provincial Hospital', area: 'Medical District' },
    { name: 'University Gate', area: 'Campus' },
    { name: 'Barangay Hall', area: 'Residential' },
    { name: 'Public Market', area: 'Market Area' },
    { name: 'Bus Terminal', area: 'Transport Hub' },
    { name: 'Jeepney Terminal', area: 'Transport Hub' },
    { name: 'Parish Church', area: 'Town Proper' },
    { name: 'Municipal Park', area: 'Central' },
    { name: 'Sports Complex', area: 'Recreation' },
    { name: 'Police Station', area: 'Government District' },
    { name: 'Fire Station', area: 'Government District' },
    { name: 'Elementary School', area: 'Residential' },
    { name: 'High School', area: 'Residential' },
    { name: 'Wet Market', area: 'Market Area' },
    { name: 'Dry Goods Section', area: 'Market Area' },
    { name: 'Rural Bank', area: 'Downtown' },
    { name: 'Post Office', area: 'Government District' },
    { name: 'Memorial Park', area: 'North' },
    { name: 'Coastal Road', area: 'Seaside' },
    { name: 'Highway Junction', area: 'Transport Hub' },
    { name: 'Subdivision Gate', area: 'Residential' },
    { name: 'Plaza Rizal', area: 'Town Proper' },
    { name: 'Covered Court', area: 'Recreation' },
  ],
};
